// Predefined daily green actions catalog
const ACTIONS_CATALOG = [
  {
    key: 'used_metro',
    name: 'Used Metro / Public Transit',
    category: 'transport',
    carbon_saved: 2.5,
    xp_earned: 20,
    eco_points_earned: 15,
    icon: '🚇',
    description: 'Chose public transit over a personal vehicle',
  },
  {
    key: 'carpooled',
    name: 'Carpooled to Work / College',
    category: 'transport',
    carbon_saved: 2.0,
    xp_earned: 15,
    eco_points_earned: 12,
    icon: '🚗',
    description: 'Shared a car ride instead of driving solo',
  },
  {
    key: 'walked_cycled',
    name: 'Walked or Cycled Instead of Driving',
    category: 'transport',
    carbon_saved: 1.8,
    xp_earned: 25,
    eco_points_earned: 20,
    icon: '🚴',
    description: 'Used human-powered transport for your commute',
  },
  {
    key: 'avoided_plastic',
    name: 'Avoided Single-Use Plastic',
    category: 'general',
    carbon_saved: 0.3,
    xp_earned: 10,
    eco_points_earned: 8,
    icon: '♻️',
    description: 'Said no to plastic bottles, straws, or bags',
  },
  {
    key: 'reusable_bag',
    name: 'Used Reusable Bag for Shopping',
    category: 'shopping',
    carbon_saved: 0.2,
    xp_earned: 8,
    eco_points_earned: 6,
    icon: '👜',
    description: 'Brought your own bag to the store',
  },
  {
    key: 'plant_based_meal',
    name: 'Ate a Plant-Based Meal',
    category: 'food',
    carbon_saved: 1.5,
    xp_earned: 15,
    eco_points_earned: 12,
    icon: '🥗',
    description: 'Chose a vegetarian or vegan meal',
  },
  {
    key: 'short_shower',
    name: 'Took a Short Shower (< 5 min)',
    category: 'energy',
    carbon_saved: 0.5,
    xp_earned: 10,
    eco_points_earned: 8,
    icon: '🚿',
    description: 'Conserved water with a quick shower',
  },
  {
    key: 'turned_off_lights',
    name: 'Turned Off Lights When Leaving',
    category: 'energy',
    carbon_saved: 0.3,
    xp_earned: 5,
    eco_points_earned: 4,
    icon: '💡',
    description: 'Saved electricity by switching off unused lights',
  },
  {
    key: 'unplugged_devices',
    name: 'Unplugged Devices on Standby',
    category: 'energy',
    carbon_saved: 0.4,
    xp_earned: 8,
    eco_points_earned: 6,
    icon: '🔌',
    description: 'Reduced phantom energy use',
  },
  {
    key: 'ate_local_food',
    name: 'Ate Locally Sourced Food',
    category: 'food',
    carbon_saved: 1.0,
    xp_earned: 12,
    eco_points_earned: 10,
    icon: '🌾',
    description: 'Chose local produce over imported goods',
  },
  {
    key: 'second_hand_purchase',
    name: 'Bought Second-Hand / Thrifted',
    category: 'shopping',
    carbon_saved: 3.0,
    xp_earned: 20,
    eco_points_earned: 18,
    icon: '🔄',
    description: 'Gave a used item a new life',
  },
  {
    key: 'no_car_day',
    name: 'Had a Car-Free Day',
    category: 'transport',
    carbon_saved: 4.0,
    xp_earned: 30,
    eco_points_earned: 25,
    icon: '🚫🚗',
    description: 'Went the whole day without using a car',
  },
];

module.exports = { ACTIONS_CATALOG };
